# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
