# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
