# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 04:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images/events', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(blank=True, verbose_name='Discription')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('unpublish', 'Unpublish'), ('publish', 'Publish')], default='unpublish', max_length=10, verbose_name='Publish/Unpublish')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('age', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Age Integer only.', regex='^0*[1-9][0-9]*$')], verbose_name='Age')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('contact', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Contact number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact')),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ofctv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('all', 'all'), ('i-league', 'i-league'), ('champions-league', 'champions-league'), ('interview', 'interview'), ('documentary', 'documentary')], default='all', max_length=20, verbose_name='data-cat')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PhotoDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='images/photo-of-day', verbose_name='Image')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('status', models.CharField(choices=[('unpublish', 'Unpublish'), ('publish', 'Publish')], default='unpublish', max_length=10, verbose_name='Publish/Unpublish')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='join',
            unique_together=set([('name', 'contact')]),
        ),
    ]
