# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(verbose_name='Discription'),
        ),
    ]
