# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.CharField(default='0', max_length=2)),
                ('score2', models.CharField(default='0', max_length=2)),
                ('date', models.DateField()),
                ('result', models.BooleanField(default='0')),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='league.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pld', models.IntegerField()),
                ('w', models.IntegerField(blank=True)),
                ('d', models.IntegerField(blank=True)),
                ('l', models.IntegerField(blank=True)),
                ('gf', models.IntegerField(blank=True)),
                ('ga', models.FloatField(max_length=4)),
                ('gd', models.FloatField(max_length=4)),
                ('pts', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='fixtures',
            unique_together=set([('league_name', 'team1', 'team2')]),
        ),
    ]
