# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20161001_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='score1',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='score2',
            field=models.CharField(blank=True, default=None, max_length=2),
        ),
    ]
