# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=100, verbose_name='League name')),
                ('start_date', models.DateField(verbose_name='Starting Date')),
                ('end_date', models.DateField(verbose_name='Ending Date')),
            ],
        ),
        migrations.CreateModel(
            name='OzonefcTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, verbose_name='Enter the Team name')),
                ('team_short_name', models.CharField(max_length=50, verbose_name='Enter the short name')),
                ('team_logo', models.ImageField(upload_to='images/team_logo', verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Player name')),
                ('player_position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward'), ('allrounder', 'Allrounder'), ('--------', '--------')], default='--------', max_length=50, verbose_name='Playing position')),
                ('jersy_number', models.CharField(max_length=3, verbose_name='Jersy number')),
                ('dob', models.DateField(verbose_name='DOB')),
                ('born_state', models.CharField(max_length=100, verbose_name='Born state')),
                ('nationality', models.CharField(max_length=50, verbose_name='Nationality')),
                ('about_player', models.TextField(verbose_name='About player')),
                ('image_player', models.ImageField(upload_to='images/image-player', verbose_name='Image')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.OzonefcTeam', verbose_name='OzoneFC Team name')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, verbose_name='Enter the Team name')),
                ('team_short_name', models.CharField(max_length=50, verbose_name='Enter the short name')),
                ('team_logo', models.ImageField(upload_to='images/team_logo', verbose_name='logo')),
                ('league_name', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='league.League')),
            ],
        ),
    ]
