# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
