# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_league_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='league.League'),
        ),
    ]
