# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-03 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20161003_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.OzonefcTeam', verbose_name='OzoneFC Team name'),
        ),
    ]
